<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/3
 * Time: 10:29
 */
namespace App\HttpController\Api;
use App\lib\Redis;
use EasySwoole\Component\Di;
use EasySwoole\EasySwoole\Config;
use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Mysqli\Mysqli;

class Index extends Controller
{
    function index()
    {

        $db = Di::getInstance()->get('MYSQL');
        $data = $db->get('wufu_member');//获取一个表的数据

        return $this->writeJson(1,$data,'api模块操作成功');

    }

    /**
     *   输出 action名称  return fasle 不执行;
     */
    protected function onRequest(?string $action): ?bool
    {
        var_dump($action);
        return true;
    }


    public function getRedis(){
//        $this->response()->write('1111');
//        $redis = Redis::getInstance();
        #注册
        $redis = Di::getInstance()->get("REDIS");
        $redis->set('haha',"111231132113",66);
        $value = $redis->get('haha');
        return $this->writeJson(1,$value,'api模块操作成功');

    }


    public function onException(\Throwable $throwable): void
    {

        $this->writeJson(400,[],'系統一場');
//        parent::onException($throwable); // TODO: Change the autogenerated stub
    }

}

